### ISSUE TITLE
Replay parsing failures

### ISSUE THREAD

**Issue by eudaimonstro** [ggtracker/sc2reader#125]
Trying to load replays at load_level=2 and sc2reader errors out with the following stack trace:

> Traceback (most recent call last):
>   File "main.py", line 443, in <module>
>     main(sys.argv[1:])
>   File "main.py", line 185, in main
>     replay_list = list(replays)
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/factories/sc2factory.py", line 146, in load_all
>     yield self._load(cls, resource, filename=filename, options=options)
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/factories/sc2factory.py", line 151, in _load
>     obj = cls(resource, filename=filename, factory=self, **options)
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/resources.py", line 301, in __init__
>     self._read_data(data_file, self._get_reader(data_file))
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/resources.py", line 893, in _read_data
>     self.raw_data[data_file] = reader(data, self)
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/readers.py", line 274, in __call__
>     for i in range(data.read_bits(5))
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/readers.py", line 274, in <listcomp>
>     for i in range(data.read_bits(5))
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/readers.py", line 197, in <listcomp>
>     for i in range(
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/decoders.py", line 210, in read_uint32
>     data = self._buffer.read_uint32()
>   File "/home/steve/workspace/trueskill/venv/lib/python3.7/site-packages/sc2reader/decoders.py", line 91, in read_uint32
>     return self._unpack_int(self.read(4))[0]
> struct.error: unpack requires a buffer of 4 bytes

Script runs successfully when load_level=0

Here's the relevant output of sc2parse (only the errors):
[pastebin](https://pastebin.com/3z3bCiWF)

Here are archives of the offending replays:
[sc2reader_replays_1.zip](https://github.com/ggtracker/sc2reader/files/5170538/sc2reader_replays_1.zip)
[sc2reader_replays_2.zip](https://github.com/ggtracker/sc2reader/files/5170539/sc2reader_replays_2.zip)
[sc2reader_replays_3.zip](https://github.com/ggtracker/sc2reader/files/5170540/sc2reader_replays_3.zip)
[sc2reader_replays_4.zip](https://github.com/ggtracker/sc2reader/files/5170541/sc2reader_replays_4.zip)
[sc2reader_replays_5.zip](https://github.com/ggtracker/sc2reader/files/5170542/sc2reader_replays_5.zip)

**Comment by StoicLoofah** [comment]
@eudaimonstro Sorry for the slow reply. I forgot to deploy v1.6.0 that fixed parsing for StarCraft 2 5.0 replays. v1.5.0, which is what I suspect you had, did not work for these new replays. Can you see if it's working for you now?
