### ISSUE TITLE
Warning when compile documentation (missing 'PersonDict' & 'AttributeDict')

### ISSUE THREAD

**Issue by dragokas** [ggtracker/sc2reader#159]
In attempt to compile documentation:
```
docs\make.bat html
```
you're receiving:
```
Running Sphinx v4.3.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 20 source files that are out of date
updating environment: [new config] 20 added, 0 changed, 0 removed
reading sources... [100%] utilities
WARNING: autodoc: failed to import class 'PersonDict' from module 'sc2reader.utils'; the following exception was raised:

Traceback (most recent call last):
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\util\inspect.py", line 448, in
safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'sc2reader.utils' has no attribute 'PersonDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\ext\autodoc\importer.py", line
110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\ext\autodoc\__init__.py", line
332, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\ext\autodoc\__init__.py", line
2780, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\util\inspect.py", line 464, in
safe_getattr
    raise AttributeError(name) from exc
AttributeError: PersonDict

WARNING: autodoc: failed to import class 'AttributeDict' from module 'sc2reader.utils'; the following exception was rais
ed:
Traceback (most recent call last):
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\util\inspect.py", line 448, in
safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'sc2reader.utils' has no attribute 'AttributeDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\ext\autodoc\importer.py", line
110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\ext\autodoc\__init__.py", line
332, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\ext\autodoc\__init__.py", line
2780, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "c:\users\alex\appdata\local\programs\python\python38-32\lib\site-packages\sphinx\util\inspect.py", line 464, in
safe_getattr
    raise AttributeError(name) from exc
AttributeError: AttributeDict

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] utilities
generating indices... genindex py-modindex done
highlighting module code... [100%] sc2reader.utils
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in build\html.

Build finished. The HTML pages are in build/html.
```
At the moment the following branch is used until it is merged: https://github.com/cclauss/sc2reader/tree/patch-4
(see: https://github.com/ggtracker/sc2reader/issues/157 )

**Comment by cclauss** [comment]
https://github.com/ggtracker/sc2reader/commit/a194b677c5f702c6d122cb956a076a39b324478f#diff-81c6d43d1eb593771f0bcd4a26185c73edad27e6ce6834344243927d46953262L51
Removed `PersonDict` in 2016.
