### ISSUE TITLE
AttributeError: 'Replay' object has no attribute 'expansion'

### ISSUE THREAD

**Issue by bearxu83** [ggtracker/sc2reader#49]
https://github.com/ggtracker/sc2reader/blob/5f189ae405af066f0beb99793ab70668979084b7/sc2reader/resources.py#L184

I think here it is a typo that misspells "expansion".

**Comment by StoicLoofah** [comment]
Good find! Can you submit a PR to fix it?

**Comment by bearxu83** [comment]
It seems that now the sc2reader can't parse the official replay packs released by sc2 official machine learning api because these replay packs hide much basic information. I will try to use sc2protocol first then I will try to see how to fix them.

I don't know why sc2reader don't use sc2protocol to parse the replay files.

**Comment by dsjoerg** [comment]
@bearxu83 it's because sc2reader was written long before s2protocol existed

**Comment by JohnSegerstedt** [comment]
The issue is still not solved.
Installed sc2reader today and got the following error:



RESTART: C:/Users/John/Desktop/Chalmers/year3/LP3=DATX02_Bachelor_Thesis/DATX02/sc2reader_python/prettyPrinter.py 
Traceback (most recent call last):
  File "C:/Users/John/Desktop/Chalmers/year3/LP3=DATX02_Bachelor_Thesis/DATX02/sc2reader_python/prettyPrinter.py", line 31, in <module>
    main()
  File "C:/Users/John/Desktop/Chalmers/year3/LP3=DATX02_Bachelor_Thesis/DATX02/sc2reader_python/prettyPrinter.py", line 27, in main
    replay = sc2reader.load_replay(path)
  File "C:\Program Files\Python36\lib\site-packages\sc2reader-0.7.0rc0-py3.6.egg\sc2reader\factories\sc2factory.py", line 85, in load_replay
    return self.load(Replay, source, options, **new_options)
  File "C:\Program Files\Python36\lib\site-packages\sc2reader-0.7.0rc0-py3.6.egg\sc2reader\factories\sc2factory.py", line 137, in load
    return self._load(cls, resource, filename=filename, options=options)
  File "C:\Program Files\Python36\lib\site-packages\sc2reader-0.7.0rc0-py3.6.egg\sc2reader\factories\sc2factory.py", line 146, in _load
    obj = cls(resource, filename=filename, factory=self, **options)
  File "C:\Program Files\Python36\lib\site-packages\sc2reader-0.7.0rc0-py3.6.egg\sc2reader\resources.py", line 273, in __init__
    self.datapack = self._get_datapack()
  File "C:\Program Files\Python36\lib\site-packages\sc2reader-0.7.0rc0-py3.6.egg\sc2reader\resources.py", line 593, in _get_datapack
    if callback(self):
  File "C:\Program Files\Python36\lib\site-packages\sc2reader-0.7.0rc0-py3.6.egg\sc2reader\resources.py", line 581, in <lambda>
    self.register_datapack(datapacks['HotS']['24764'], lambda r: r.expansion == 'HotS' and 24764 <= r.build)
AttributeError: 'Replay' object has no attribute 'expansion'
>>>


And if I check the resources.py file, expansion is still misspelled.

**Comment by cclauss** [comment]
Which line number in __resources.py__?

**Comment by StoicLoofah** [comment]
@JohnSegerstedt it appears that you're using an outdated version of sc2reader. The path in your stack trace says `0.7.0rc0` whereas we're currently on [version 1.3.1](https://github.com/ggtracker/sc2reader/releases/tag/v1.3.1)

How did you install sc2reader? It's possible that you may have followed outdated installation instructions, in which case we can provide new ones
